### ISSUE TITLE
Error: Couldn't find intersection

### ISSUE THREAD

**Issue by jsg2021** [babel/minify#904]
**Describe the bug**

After updating to 0.5, I started getting these errors... 

**Stack Trace**

```
./node_modules/regenerator-runtime/runtime-module.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find intersection



  Error: Child compilation failed:
  Module build failed (from ./node_modules/babel-loader/lib/index.js):
  Error: Couldn't find intersection
  
  - ancestry.js:153 NodePath.getDeepestCommonAncestorFrom
    [app]/[@babel]/traverse/lib/path/ancestry.js:153:11
  
  - index.js:244 getSegmentedSubPaths
    [app]/[babel-plugin-minify-builtins]/lib/index.js:244:14
  
  - index.js:92 BuiltInReplacer.replace
    [app]/[babel-plugin-minify-builtins]/lib/index.js:92:31
  
  - index.js:205 PluginPass.exit
    [app]/[babel-plugin-minify-builtins]/lib/index.js:205:27
  
  - visitors.js:193 newFn
    [app]/[@babel]/traverse/lib/visitors.js:193:21
  
  - context.js:53 NodePath._call
    [app]/[@babel]/traverse/lib/path/context.js:53:20
  
  - context.js:40 NodePath.call
    [app]/[@babel]/traverse/lib/path/context.js:40:17
  
  - context.js:97 NodePath.visit
    [app]/[@babel]/traverse/lib/path/context.js:97:8
  
  - context.js:118 TraversalContext.visitQueue
    [app]/[@babel]/traverse/lib/context.js:118:16
  
  - context.js:90 TraversalContext.visitSingle
    [app]/[@babel]/traverse/lib/context.js:90:19
  
  - context.js:146 TraversalContext.visit
    [app]/[@babel]/traverse/lib/context.js:146:19
  
  - index.js:94 Function.traverse.node
    [app]/[@babel]/traverse/lib/index.js:94:17
  
  - index.js:76 traverse
    [app]/[@babel]/traverse/lib/index.js:76:12
  
  - index.js:88 transformFile
    [app]/[@babel]/core/lib/transformation/index.js:88:29
  
  - index.js:45 runSync
    [app]/[@babel]/core/lib/transformation/index.js:45:3

```

**Configuration**

`babel-minify preset in babel config`

babel-minify version: `0.5.0`

babel version : `7.1.0`

babel-minify-config:

```json5
loader: require.resolve('babel-loader'),
options: {
	babelrc: false,
	sourceType: 'unambiguous',
	compact: PROD,
	presets: [
		require.resolve('./babel.config.js'),
		[require.resolve('babel-preset-minify'), {
			mangle: false,
			deadcode: false,
			// simplify: false,
			evaluate: false,
		}]
	]
}
```

babelrc:

```json5
{
    sourceType: 'unambiguous',
    compact: false,
    presets: [
        ['@babel/preset-env', {
            shippedProposals: true,
            targets: [
                '> 1% in US',
                'last 2 versions',
                'not dead',
            ]
        }],
        '@babel/preset-flow',
        '@babel/preset-react',
    ],
    plugins: [
        '@babel/plugin-transform-runtime',
        ['@babel/plugin-proposal-decorators', { legacy: true }],
        ['@babel/plugin-proposal-class-properties', { loose: true }],
        '@babel/plugin-proposal-export-default-from',
        '@babel/plugin-proposal-export-namespace-from',
        '@babel/plugin-syntax-dynamic-import'
    ]
}
```

**Comment by wavded** [comment]
Same

**Comment by ZempTime** [comment]
I'm also getting a pretty much identical stack trace when I updated to 
> "babel-preset-minify": "^0.5.0-alpha.9",

**Comment by driesd** [comment]
I'm also getting the same stack trace with "babel-preset-minify": "^0.5.0-alpha.9".

**Comment by pkuczynski** [comment]
Have the same problem. For me it crashes when optimizing following file:

```
const hasValue = value => Boolean(value) || value === 0

export default hasValue
```

**Comment by wende60** [comment]
confirm that @goozler solution works also for me with the same problems...

**Comment by derwaldgeist** [comment]
Same here. I tried to upgrade to Babel 7 because of https://github.com/babel/minify/issues/556, and now the error journey just continues... Pretty disappointing experience.

**Comment by williaster** [comment]
Same error

**Comment by linorabolini** [comment]
Same issue, downgraded to 0.3.0 and it works okay now.

"babel-preset-minify": "^0.3.0",

**Comment by crespo5** [comment]
Same issue... any solution? For me not works in CLI and in babel preset.

**Comment by kasperpeulen** [comment]
I downgraded to ^0.4.3 to get it working.

**Comment by CloudPower97** [comment]
I'm experiencing this problem as well... Any solutions?

**Comment by termitek12** [comment]
For me this is a problem when I minify multiple files or some files that are > 1MB.

If I minify files one by one - everything is ok.

However minify files one by one is annoying and this should be fixed ASAP.

**Comment by finom** [comment]
I tried to use `babel-plugin-minify-builtins` without any other plugins but still get the same bug.

**Comment by william-bratches** [comment]
Same issue here.

**Comment by fatlard1993** [comment]
Same issue here. Changing ```'minify'``` to ```['minify', { builtIns: false }]``` as @goozler suggested worked for me for now.

**Comment by aprilmintacpineda** [comment]
In my case this happens intermittently (I'm not sure when) but I've never experienced this when building locally. However, building using `runners` on GitLab, this happens frequently (about 50 to 60 percent of the time).

**Comment by xixilive** [comment]
In my case: 

> Note: `Math.ceil` and `Math.floor`

```js
// throw Error: Couldn't find intersection
function(){
  const gen = () => seq.substr(Math.ceil(Math.random() * 1e5) % len, 1)
}

// not throw
function(){
  const gen = () => seq.substr(Math.floor(Math.random() * 1e5) % len, 1)
}
```

**Comment by aprilmintacpineda** [comment]
I started to notice this error when I added this polyfill. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill

**Comment by bderblatter** [comment]
I'm just following the directions [here](https://babeljs.io/docs/en/babel-preset-minify) and I'm getting this error:

```
$ npm run js

> assets@0.1.0 js /Code/front-end-tools
> babel ../assets/js/modules --out-dir ../assets/dist/js --presets minify

Error: Couldn't find intersection
    at NodePath.getDeepestCommonAncestorFrom (/Code/front-end-tools/node_modules/@babel/traverse/lib/path/ancestry.js:153:11)
    at getSegmentedSubPaths (/Code/front-end-tools/node_modules/babel-plugin-minify-builtins/lib/index.js:244:14)
    at BuiltInReplacer.replace (/Code/front-end-tools/node_modules/babel-plugin-minify-builtins/lib/index.js:92:31)
    at PluginPass.exit (/Code/front-end-tools/node_modules/babel-plugin-minify-builtins/lib/index.js:205:27)
    at newFn (/Code/front-end-tools/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Code/front-end-tools/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Code/front-end-tools/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Code/front-end-tools/node_modules/@babel/traverse/lib/path/context.js:97:8)
    at TraversalContext.visitQueue (/Code/front-end-tools/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Code/front-end-tools/node_modules/@babel/traverse/lib/context.js:90:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! assets@0.1.0 js: `babel ../assets/js/modules --out-dir ../assets/dist/js --presets minify`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the assets@0.1.0 js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2019-04-25T21_53_04_927Z-debug.log
```

**Comment by meduzen** [comment]
I encountered this bug suddenly, only while watching file changed (_webpack watch_), but have no idea why has no changes were made to my build setup. Running file compilation for production was still fine.

Solved it by downgrading from 0.5.0 to 0.4.3, as suggested by @kasperpeulen. The `builtIns` and `useBuiltIns` proposals didn’t solved anything in my case.

Here’s my `.babelrc`:
```json
{
    "comments": false,
    "presets": ["@babel/preset-env"],
    "env":
    {
        "development": { "presets": ["minify"] },
        "production": { "presets": ["minify"] }
    }
}
```

<details>

<summary>and the `devDependencies` part of the `package.json`</summary>

```json
"devDependencies": {
    "@babel/cli": "^7.4.4",
    "@babel/core": "^7.4.4",
    "@babel/preset-env": "^7.4.4",
    "babel-loader": "^8.0.5",
    "babel-preset-minify": "^0.4.3",
    "browser-sync": "^2.26.5",
    "browser-sync-webpack-plugin": "^2.2.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^5.0.2",
    "cross-env": "^5.1.4",
    "css-loader": "^2.1.1",
    "cssnano": "^4.1.10",
    "dotenv": "^8.0.0",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "mini-css-extract-plugin": "^0.5.0",
    "node-sass": "^4.12.0",
    "postcss-loader": "^3.0.0",
    "postcss-preset-env": "^6.5.0",
    "sass-loader": "^7.1.0",
    "vue-loader": "^15.0.9",
    "vue-template-compiler": "^2.6.10",
    "webpack": "^4.29.0",
    "webpack-build-notifier": "^1.0.2",
    "webpack-cli": "^3.3.0",
    "webpack-merge": "^4.1.2"
}
```

</details>

**Comment by dtvn** [comment]
> 
> 
> For me this is a problem when I minify multiple files or some files that are > 1MB.
> 
> If I minify files one by one - everything is ok.
> 
> However minify files one by one is annoying and this should be fixed ASAP.

I got a same problem today too.

![image](https://user-images.githubusercontent.com/43217335/61800721-c27efa00-ae57-11e9-9a89-3ae6da8c08ea.png)

**Comment by MichaelOrtho** [comment]
In my case it throws this if I use `Math.floor`. If I change it to `Math.round` or some other, it passes.

**Comment by TheDudeFromCI** [comment]
I've found this error to be thrown when using `Math.max`. Commenting that line out allows it to solve.

**Comment by rfossella** [comment]
Oddly, while the _'builtIns': false_ did work, it did not help me when using babel minify in NPM.  I'm actually not even sure how to put that override in the CLI - e.g. npm run build.

**Comment by Singtah** [comment]
> I am experiencing the same problem right now, what's weird is that it works on my PC locally, but when I deploy it to Heroku it crashes
> 
> ```
> 2019-01-20T02:21:49.246316+00:00 app[web.1]:     at NodePath.getDeepestCommonAncestorFrom (/app/node_modules/@babel/traverse/lib/path/ancestry.js:153:11)
> 2019-01-20T02:21:49.246318+00:00 app[web.1]:     at getSegmentedSubPaths (/app/node_modules/babel-plugin-minify-builtins/lib/index.js:244:14)
> 2019-01-20T02:21:49.246319+00:00 app[web.1]:     at BuiltInReplacer.replace (/app/node_modules/babel-plugin-minify-builtins/lib/index.js:92:31)
> 2019-01-20T02:21:49.246321+00:00 app[web.1]:     at PluginPass.exit (/app/node_modules/babel-plugin-minify-builtins/lib/index.js:205:27)
> 2019-01-20T02:21:49.246322+00:00 app[web.1]:     at newFn (/app/node_modules/@babel/traverse/lib/visitors.js:193:21)
> 2019-01-20T02:21:49.246323+00:00 app[web.1]:     at NodePath._call (/app/node_modules/@babel/traverse/lib/path/context.js:53:20)
> 2019-01-20T02:21:49.246325+00:00 app[web.1]:     at NodePath.call (/app/node_modules/@babel/traverse/lib/path/context.js:40:17)
> 2019-01-20T02:21:49.246326+00:00 app[web.1]:     at NodePath.visit (/app/node_modules/@babel/traverse/lib/path/context.js:97:8)
> 2019-01-20T02:21:49.246327+00:00 app[web.1]:     at TraversalContext.visitQueue (/app/node_modules/@babel/traverse/lib/context.js:118:16)
> 2019-01-20T02:21:49.246329+00:00 app[web.1]:     at TraversalContext.visitSingle (/app/node_modules/@babel/traverse/lib/context.js:90:19)
> 2019-01-20T02:21:49.261822+00:00 app[web.1]: npm ERR! code ELIFECYCLE
> 2019-01-20T02:21:49.262262+00:00 app[web.1]: npm ERR! errno 1
> 2019-01-20T02:21:49.263298+00:00 app[web.1]: npm ERR! fonis@0.0.1 start: `set NODE_ENV=production && babel lib/js --out-dir public/js && node ./bin/www`
> 2019-01-20T02:21:49.263458+00:00 app[web.1]: npm ERR! Exit status 1```
> ```

Same issue here, ok locally but not on Heroku. Would appriciate to know how you fixed it ?

**Comment by rfossella** [comment]
Hi.
As stated in the post, when I did not minify it displayed which file was causing the issue.  I tried to minify ONLY that program and it worked.  So I created two separate compiles - 1 for the offending program and another for all the others.

**Comment by dogia** [comment]
Take care if you are using Math.

`let movX = Math.abs(currentPosX - this.path[0].posX);
 let movY = Math.abs(currentPosY - this.path[0].posY);`

I was solve my issue changing Math.abs

`let movX = currentPosX - this.path[0].posX;
 let movY = currentPosY - this.path[0].posY;

  if(movX < 0) movX = (-1) * movX;
  if(movY < 0) movY = (-1) * movY;`

**Comment by Mitsunee** [comment]
just happend across this problem with `Math.floor()` in my little library project. I currently have 2 js files, both of which have the same method `convert()` in their classes, which uses `Math.floor()` a bunch. Building these files standalone (see package.json) works fine, but if I try `npx babel src -d builds` it suddenly gets the same error as op.

Here's the link to the commit where I pushed my current configs: https://github.com/Mitsunee/fox-timers/commit/5a57968d9209a5a34f04952e9954359ab9e80b40 

And a screenshot of the error as I'm getting it:
![Screenshot_20201201_155801](https://user-images.githubusercontent.com/19474909/100756895-ff64e480-33ed-11eb-8d4c-c58b877c2fa7.png)

**Comment by sivaraj-v** [comment]
Any update ?

**Comment by joshuambg** [comment]
Still an issue for me. 
```
"@babel/core": "^7.4.3",
"babel-minify": "^0.5.1",
"babel-preset-minify": "^0.5.1",
"webpack": "^5.62.1",
```

Solved with 
```
 "presets": [["minify", { "builtIns": false }]],
```

**Comment by ElPrudi** [comment]
Yes, still an issue for me. 
Had to use
```
 "presets": [["minify", { "builtIns": false, "mangle": false }]]
```

**Comment by esauvisky** [comment]
Still an issue. For me, it happens because of `String.fromCharCode()`. Setting builtIns to false solves it.

**Comment by jkufrin** [comment]
> Yes, still an issue for me. Had to use
> 
> ```
>  "presets": [["minify", { "builtIns": false, "mangle": false }]]
> ```

Thanks! That worked for me. And for those using gulp-babel-minify:

` 
.pipe(minify({
    "builtIns": false, "mangle": false 
}))
`

**Comment by xhemals** [comment]
Still had this issue, workaround I had for still being able to have minified code in my build was this:
1. Setup different environments in `babel.config.json` 
```
{
  "env": {
    "dev": {
       "presets": [["minify", { "builtIns": false}]]
     },
    "build": {
      "presets": ["minify"]
    }
  }
}
```
2. In `package.json`, declare `BABEL_ENV=dev` at the start of my `npm run dev`. And `BABEL_ENV=build` at the start of my `nom run build` command.

Hope this helps anyone still having this issue in 2024!

**Comment by hopolivier** [comment]
Hello,
In case someone would like to run babel-minify from the command line, with builtins minifying deactivated, I tried :

`babel-minify <filename or directory> --out-dir <output directory> --builtIns false`

and it worked for me.

**Comment by sidewayss** [comment]
What is meant by "intersection" in this context?

Late 2024 and it's `"mangle"` that's triggering it for me.  I don't have `Math.` in these files.  But I want to mangle these files and it works for all the other files in this project.  For now I'll have to minify this one file separately and live with the slightly larger file size, but I'd like to figure out what the offending identifier is, or at least which line of code it is. The error message does not provide such information.  It looks like the stack traces in the comment above. 

I have looked at the minify plugin source code, but the "intersection" error is from traversal inside the plugin, so nothing there. The error itself occurs at
> NodePath.getDeepestCommonAncestorFrom (C:\Apache24\htdocs\html-elements\node_modules\@babel\traverse\lib\path\ancestry.js:113:11)

So it could be trying to find a superclass or an import that it can't resolve?  I'm guessing. Looks like I'm going to have to trial-and-error debug by reduction: remove arbitrary bits and pieces from the file until the error goes away...

ps - I cannot use `"mangle":false` unless I also use `"builtIns:false"`.

**Comment by sidewayss** [comment]
Late 2024, same error, two options, each with their own reason for throwing:
1) `"builtIns"` - `Math.max()` and `Math.min()` cause the error.  I am using `.floor()`, `.ceil()`, and `.pow()` with no issue. I am also using both `.max()` and `.min()` in another file in this same repo with no error...
2) `"mangle"` - This works: 
    ```js
    Class C {
        method(arg = (this.prop == "foo")) {}
    }
    ```
    This throws the error:
    ```js
    const FOO = "foo";
    Class C {
        method(arg = (this.prop == FOO)) {}
    }
    ```
    The `FOO` constant is used elsewhere in the file without any issue. Thankfully this error occurs only once and is easily worked around.  Name mangling is one of my favorite minification features.  I can live without `"builtIns"`, certainly for this project.
